language: node

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':10.0'
  - Xvfb :10 -screen 0 1920x1080x60 > /dev/null 2>&1 &

script:
  - npm run e2e
  - npm run test-single-run

notifications:
  slack: $SLACK_TOKEN
